"""Initial migration.

Revision ID: 2fe9b22435ea
Revises: 
Create Date: 2025-09-14 10:34:11.766003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe9b22435ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('default_daily_hours', sa.Float(), nullable=True),
    sa.Column('default_working_days', sa.String(length=255), nullable=True),
    sa.Column('working_hours_start', sa.Time(), server_default=sa.text("'07:00:00'"), nullable=False),
    sa.Column('working_hours_end', sa.Time(), server_default=sa.text("'18:00:00'"), nullable=False),
    sa.Column('max_idle_minutes', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('idle_to_break_minutes', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('long_break_prompt_minutes', sa.Integer(), server_default=sa.text('90'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('microsoft_oid', sa.String(length=100), nullable=True),
    sa.Column('default_daily_hours', sa.Float(), nullable=True),
    sa.Column('default_working_days', sa.String(length=255), nullable=True),
    sa.Column('session_start_time', sa.Time(), server_default=sa.text("'09:00:00'"), nullable=False),
    sa.Column('session_end_time', sa.Time(), server_default=sa.text("'18:00:00'"), nullable=False),
    sa.Column('overtime_end_time', sa.DateTime(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('microsoft_oid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('overtime_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allocated_by', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['allocated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clock_in_time', sa.DateTime(), nullable=False),
    sa.Column('clock_out_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_worked_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=True),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('window_title', sa.String(length=512), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automated_state_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=True),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=False),
    sa.Column('break_start_time', sa.DateTime(), nullable=False),
    sa.Column('break_end_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idle_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=False),
    sa.Column('idle_start_time', sa.DateTime(), nullable=False),
    sa.Column('idle_end_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_location_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_location_log')
    op.drop_table('idle_entry')
    op.drop_table('break_entry')
    op.drop_table('automated_state_change')
    op.drop_table('application_usage')
    op.drop_table('activity_log')
    op.drop_table('time_entry')
    op.drop_table('overtime_allocation')
    op.drop_table('user')
    op.drop_table('company_config')
    # ### end Alembic commands ###
